name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Configure Git
        run: |
          git config --global user.email "namankhurana9083@gmail.com"
          git config --global user.name "naman9083"

      - name: Deploy to Gh-pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run deploy