name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Deploy to Gh-pages
        # setup credentials
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
        run: npm run deploy
          
        
        
